change Ituma Called-Station-Id to 'Location;SSID'
travelping/ergw_aaa pull request #98
Opened 2020-12-09 13:32 UTC by RoadRunnr

2020-12-09 13:32 UTC, RoadRunnr commented
mostly untested

2020-12-09 14:10 UTC, vkatsuba approved these changes

2020-12-09 14:22 UTC, vkatsuba requested changes

2020-12-09 14:22 UTC, vkatsuba commented on src/ergw_aaa_radius.erl
> +    io_lib:format("~w", MAC).
Looks like need wrap to list `MAC`: 
```erlang 
io_lib:format("~w", [MAC]).
```

2020-12-09 14:26 UTC, vkatsuba requested changes

2020-12-09 14:26 UTC, vkatsuba commented on src/ergw_aaa_radius.erl
> +    LocId = format_eui(<< (binary_to_integer(Location)):6/bytes >>),
Judging by the data that is transmitted in `radius_SUITE.erl` the `Location` is integer. Or this wrong logic, or CT should be update

2020-12-10 10:08 UTC, vkatsuba commented on src/ergw_aaa_radius.erl
> +    io_lib:format("~w", MAC).
```suggestion
    io_lib:format("~w", [MAC]).
```

2020-12-10 11:13 UTC, vkatsuba approved these changes

2020-12-10 11:53 UTC, merged